CREATE TABLE "app_users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(150) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "role" VARCHAR(20) NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "created_at" TIMESTAMP,
    "deleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "email_verified" BOOLEAN NOT NULL DEFAULT FALSE,
    "verificationToken" VARCHAR(255),
    "verificationTokenExpiry" TIMESTAMP,
    CONSTRAINT "uk_app_users_username" UNIQUE ("username"),
    CONSTRAINT "uk_app_users_email" UNIQUE ("email")
);

CREATE TABLE "Category" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    CONSTRAINT "uk_Category_name" UNIQUE ("name")
);

CREATE TABLE "Product" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "imageUrl" VARCHAR(255),
    "name" VARCHAR(200) NOT NULL,
    "shortDescription" VARCHAR(500),
    "longDescription" TEXT,
    "price" NUMERIC(15, 2) NOT NULL,
    "stock" INT NOT NULL,
    "category_id" BIGINT NOT NULL,
    "deleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "version" BIGINT,
    CONSTRAINT "fk_product_category" FOREIGN KEY ("category_id") REFERENCES "Category" ("id")
);

CREATE TABLE "Cart" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    CONSTRAINT "uk_cart_user" UNIQUE ("user_id"),
    CONSTRAINT "fk_cart_user" FOREIGN KEY ("user_id") REFERENCES "app_users" ("id")
);

CREATE TABLE "CartItem" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "quantity" INT NOT NULL,
    "cart_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    CONSTRAINT "fk_cart_item_cart" FOREIGN KEY ("cart_id") REFERENCES "Cart" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_cart_item_product" FOREIGN KEY ("product_id") REFERENCES "Product" ("id")
);

CREATE TABLE "orders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "orderNumber" VARCHAR(40),
    "user_id" BIGINT NOT NULL,
    "creationTimestamp" TIMESTAMP,
    "total" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "status" VARCHAR(20) NOT NULL,
    "paymentMethod" VARCHAR(30),
    "stripePaymentIntentId" VARCHAR(120),
    "paymentStatus" VARCHAR(20),
    "checkoutIdempotencyKey" VARCHAR(80),
    "customerName" VARCHAR(120),
    "customerEmail" VARCHAR(150),
    "phone" VARCHAR(30),
    "addressLine1" VARCHAR(150),
    "addressLine2" VARCHAR(150),
    "city" VARCHAR(80),
    "state" VARCHAR(80),
    "postalCode" VARCHAR(20),
    "country" VARCHAR(80),
    "note" VARCHAR(500),
    CONSTRAINT "uk_orders_order_number" UNIQUE ("orderNumber"),
    CONSTRAINT "uk_orders_checkout_idempotency_key" UNIQUE ("checkoutIdempotencyKey"),
    CONSTRAINT "fk_orders_user" FOREIGN KEY ("user_id") REFERENCES "app_users" ("id"),
    CONSTRAINT "orders_status_check" CHECK ("status" IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED'))
);

CREATE TABLE "OrderItem" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    "quantity" INT NOT NULL,
    "price" NUMERIC(15, 2) NOT NULL,
    CONSTRAINT "fk_order_item_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_order_item_product" FOREIGN KEY ("product_id") REFERENCES "Product" ("id")
);

CREATE TABLE "wishlists" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "visibility" VARCHAR(10) NOT NULL,
    "share_token" VARCHAR(64),
    "is_default" BOOLEAN NOT NULL DEFAULT FALSE,
    "user_id" BIGINT NOT NULL,
    CONSTRAINT "uk_wishlists_user_name" UNIQUE ("user_id", "name"),
    CONSTRAINT "uk_wishlists_share_token" UNIQUE ("share_token"),
    CONSTRAINT "fk_wishlists_user" FOREIGN KEY ("user_id") REFERENCES "app_users" ("id")
);

CREATE TABLE "wishlist_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "wishlist_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    "desired_quantity" INT NOT NULL DEFAULT 1,
    "added_at" TIMESTAMP NOT NULL,
    CONSTRAINT "uk_wishlist_items_wishlist_product" UNIQUE ("wishlist_id", "product_id"),
    CONSTRAINT "fk_wishlist_items_wishlist" FOREIGN KEY ("wishlist_id") REFERENCES "wishlists" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_wishlist_items_product" FOREIGN KEY ("product_id") REFERENCES "Product" ("id")
);

CREATE TABLE "audit_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "action" VARCHAR(100) NOT NULL,
    "entityType" VARCHAR(100) NOT NULL,
    "entityId" BIGINT NOT NULL,
    "performedBy" VARCHAR(255) NOT NULL,
    "ipAddress" VARCHAR(45),
    "userAgent" VARCHAR(2000),
    "details" VARCHAR(2000),
    "createdAt" TIMESTAMP NOT NULL
);
